### ISSUE TITLE
PHP Parse error 

### ISSUE THREAD

**Issue by milescristi** [NabiKAZ/telegram-auto-responder#1]
PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /home/ubuntu/tgautoresp/index.php on line 112

**Comment by NabiKAZ** [comment]
Please use PHP 7.1 and later,

**Comment by milescristi** [comment]
Thanks NabiKAZ, I installed PHP 7.1 and I was able to login

However it gives me this error. Can you you help me to make it work?

index.php(62):          ExceptionErrorHandler()
  thrown in /home/ubuntu/tgautoresp/index.php on line 62

**Comment by NabiKAZ** [comment]
Do you sure for set `$group_source` and `$group_target`  variables for group address in the source code?

**Comment by milescristi** [comment]
yes I did, I already said I was able to login

I already know the chat_id numbers of source and destination groups. Is there any way to include these values in the script? it seems it cannot get the info.

I'm sorry if I talk nonsense but I'm not a programmer, I'm just trying to figure out how to make this work

**Comment by NabiKAZ** [comment]
Logging in to the system does not have related to set the variables `$group_source` and `$group_target`.

Anyway, I tested again and don't see any problem, Please check and sure the user logged-in, **joined into both source and target group**.

About use group ID instead of group URL, You can use group ID in the variables but add negative in prefix. for example be like this:
```
$group_source = '-111111111';
$group_target = '-222222222';
```
And also If you don't want use `get_info()` method for get details of group, just you can commented these lines with add `//` in the first of lines:
```
//$group_source_info = $MadelineProto->get_info($group_source);
//$group_source_id = $group_source_info['chat_id'];
```
And then use this after that:
```
$group_source_id = '111111111';
```
Note that in here you don't need add negative for prefix.
